version: '3.7'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testbd
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
    - 3306:3306
    container_name: mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    container_name: adminer

#  tomcat:
#    image: tomcat
#    restart: always
#    ports:
#      - 80:8080
#    container_name: tomcat
#    volumes:
#      - ./logs/:/usr/local/tomcat/logs/